# Generated by Django 4.1.5 on 2023-02-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
